# -*- coding: utf-8 -*-
"""crypto-sentiment-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJNzAN6dIIjFDDlxycR-7sKq1eMNtiJz
"""

import pandas as pd

trades = pd.read_csv("historical_data.csv")
sentiment = pd.read_csv("fear_greed_index.csv")

import os
os.listdir()

import pandas as pd

trades = pd.read_csv("historical_data.csv")
sentiment = pd.read_csv("fear_greed_index.csv")


print("Historical Data")
display(trades.head())

print("\nFear & Greed Data")
display(sentiment.head())

print("Historical Data Columns:")
print(trades.columns.tolist())

print("\nFear & Greed Columns:")
print(sentiment.columns.tolist())

trades['Timestamp IST'] = pd.to_datetime(trades['Timestamp IST'])
trades['Date'] = trades['Timestamp IST'].dt.date

sentiment['date'] = pd.to_datetime(sentiment['date'])
sentiment['Date'] = sentiment['date'].dt.date

df = pd.merge(
    trades,
    sentiment[['Date', 'classification', 'value']],
    on='Date',
    how='left'
)

print(df[['Date','classification','value']].head())
print(df.shape)

print(df[['classification','value']].isnull().sum())

df = df.dropna(subset=['classification'])

"""Question 1: Number of Trades by Market Sentiment"""

trade_count = df.groupby('classification').size().sort_values(ascending=False)
print(trade_count)

import matplotlib.pyplot as plt

trade_count.plot(kind='bar')
plt.title("Number of Trades by Market Sentiment")
plt.xlabel("Market Sentiment")
plt.ylabel("Number of Trades")
plt.xticks(rotation=45)
plt.show()

"""Question 2: Total Closed PnL by Sentiment"""

profit = df.groupby('classification')['Closed PnL'].sum().sort_values(ascending=False)
print(profit)

profit.plot(kind='bar')
plt.title("Total Closed PnL by Market Sentiment")
plt.ylabel("Total Profit/Loss")
plt.xticks(rotation=45)
plt.show()

"""Question 3: Average Closed PnL by Sentiment"""

avg_profit = df.groupby('classification')['Closed PnL'].mean().sort_values(ascending=False)
print(avg_profit)

avg_profit.plot(kind='bar')
plt.title("Average Closed PnL by Market Sentiment")
plt.ylabel("Average Profit/Loss")
plt.xticks(rotation=45)
plt.show()

"""Question 4: Buy vs Sell Performance"""

buy_sell = df.groupby('Side')['Closed PnL'].sum()
print(buy_sell)

buy_sell.plot(kind='bar')
plt.title("Buy vs Sell Performance")
plt.ylabel("Total Closed PnL")
plt.show()

"""Question 5: Top 10 Most Profitable Coins"""

top_coins = df.groupby('Coin')['Closed PnL'].sum().sort_values(ascending=False).head(10)
print(top_coins)

top_coins.plot(kind='bar')
plt.title("Top 10 Coins by Profit")
plt.ylabel("Total Closed PnL")
plt.show()

"""Question 6: Top 10 Traders by Profit"""

top_traders = df.groupby('Account')['Closed PnL'].sum().sort_values(ascending=False).head(10)
print(top_traders)

top_traders.plot(kind='bar')
plt.title("Top 10 Traders")
plt.ylabel("Total Closed PnL")
plt.show()

"""Question 7: Average Trade Size by Sentiment"""

avg_size = df.groupby('classification')['Size USD'].mean()
print(avg_size)

avg_size.plot(kind='bar')
plt.title("Average Trade Size by Sentiment")
plt.ylabel("Average Size (USD)")
plt.show()

"""Question 8: Average Fees by Sentiment"""

fees = df.groupby('classification')['Fee'].mean()
print(fees)

fees.plot(kind='bar')
plt.title("Average Trading Fee by Sentiment")
plt.ylabel("Average Fee")
plt.show()

"""Question 9: Winning vs Losing Trades"""

df['Result'] = df['Closed PnL'].apply(lambda x: 'Profit' if x > 0 else 'Loss')

result = pd.crosstab(df['classification'], df['Result'])
print(result)

result.plot(kind='bar', stacked=True)
plt.title("Winning vs Losing Trades")
plt.show()

"""Question 10: Correlation Between Fear & Greed Index and Profit"""

corr = df[['value','Closed PnL']].corr()
print(corr)

plt.scatter(df['value'], df['Closed PnL'], alpha=0.3)
plt.title("Fear & Greed Index vs Closed PnL")
plt.xlabel("Fear & Greed Value")
plt.ylabel("Closed PnL")
plt.show()

"""**Conclusion**
This analysis explored the relationship between market sentiment and trader performance using Bitcoin Fear & Greed Index data and historical trading records. The results show that market sentiment influences trading activity and profitability. Greed periods generally have higher trading activity, while fear periods require more cautious trading. These insights can help traders improve decision-making, manage risk effectively, and choose better entry and exit points based on market sentiment.
"""